targets:
  $default:
    builders:
      json_serializable:
        options:
          # JSONシリアライゼーション設定
          any_map: false
          checked: false
          explicit_to_json: true
          field_rename: none
          include_if_null: true

